### ISSUE TITLE
VB6 SP6 download is no longer available

### ISSUE THREAD

**Issue by chiyuki0325** [VykosX/ModernVB#6]
I cannot get required files to apply this patch. Microsoft has deleted all the downloads of [Visual Basic 6 Service Pack 6](https://www.microsoft.com/zh-cn/download/confirmation.aspx?id=5721) (Vs6sp6**B**.exe), and it's not available on Internet Archive too.

![图片](https://user-images.githubusercontent.com/73830635/222745910-5331af3d-aa97-4535-bf69-424d2accd158.png)
![图片](https://user-images.githubusercontent.com/73830635/222746088-639786b2-51f1-460c-b2e9-64d3b66bf203.png)

**Comment by VykosX** [comment]
Sorry for the long time in responding, I haven't been keeping track with this project since for all intents and purposes I considered it finished.

I uploaded my local backups of the VB6 SP6 Runtime to a "VB6 SP6 Archives" folder in the Master repository. You should be able to patch those and use ModernVB again.
